all_task_dict:
  data_provider: cls
  gleason_score: cls
  isup_grade: cls
tasks_to_run:
- isup_grade
- gleason_score
label_dict:
  data_provider:
    karolinska: 0
    radboud: 1
  gleason_score:
    0+0: 0
    3+3: 1
    3+4: 2
    3+5: 3
    4+3: 4
    4+4: 5
    4+5: 6
    5+3: 7
    5+4: 8
    5+5: 9
    negative: 10
  isup_grade:
    '0': 0
    '1': 1
    '2': 2
    '3': 3
    '4': 4
    '5': 5
