all_task_dict:
  OS: surv
  DFS: surv
  ABLATION_EMBOLIZATION_TX_ADJUVANT: cls
  AFP_AT_PROCUREMENT: reg
  AFP_NORM_RANGE_LOWER: reg
  AFP_NORM_RANGE_UPPER: reg
  AGE: reg
  AJCC_METASTASIS_PATHOLOGIC_PM: cls
  AJCC_NODES_PATHOLOGIC_PN: cls
  AJCC_PATHOLOGIC_TUMOR_STAGE: cls
  AJCC_PATHOLOGIC_TUMOR_STAGE_reduced: cls
  AJCC_STAGING_EDITION: cls
  AJCC_TUMOR_PATHOLOGIC_PT: cls
  BILIRUBIN_TOTAL: reg
  BILIRUBIN_TOTAL_NORM_RANGE_LOWER: reg
  BILIRUBIN_TOTAL_NORM_RANGE_UPPER: reg
  CHILD_PUGH_CLASSIFICATION: cls
  CREATININE_LEVEL_PRERESECTION: reg
  CREATININE_NORM_RANGE_LOWER: reg
  CREATININE_NORM_RANGE_UPPER: reg
  DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS: reg
  DEFINITIVE_SURGICAL_PROCEDURE: cls
  ECOG_SCORE: reg
  ETHNICITY: cls
  FAMILY_HISTORY_CANCER_NUMBER_RELATIVES: reg
  FAMILY_HISTORY_OF_CANCER: cls
  GRADE: cls
  HEIGHT: reg
  HEPATIC_INFLAMMATION_ADJ_TISSUE: cls
  HISTOLOGICAL_DIAGNOSIS: cls
  HISTORY_HEPATO_CARCINOMA_RISK_FACTORS: cls
  HISTORY_NEOADJUVANT_TRTYN: cls
  HISTORY_OTHER_MALIGNANCY: cls
  ICD_O_3_HISTOLOGY: cls
  ISHAK_FIBROSIS_SCORE: cls
  NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT: cls
  OTHER_HEPATO_CARCINOMA_RISK_FACTORS: cls
  PHARMACEUTICAL_TX_ADJUVANT: cls
  PLATELET_COUNT_PRERESECTION: reg
  PLATELET_NORM_RANGE_LOWER: reg
  PLATELET_NORM_RANGE_UPPER: reg
  PROSPECTIVE_COLLECTION: cls
  PROTHROMBIN_TIME_INR_AT_PROCUREMENT: reg
  PROTHROMBIN_TIME_NORM_RANGE_UPPER: reg
  PROTHROM_TIME_INR_NORM_RANGE_LOWER: reg
  RACE: cls
  RADIATION_TREATMENT_ADJUVANT: cls
  RESIDUAL_TUMOR: cls
  RETROSPECTIVE_COLLECTION: cls
  SAMPLE_COUNT: reg
  SERUM_ALBUMIN_NORM_RANGE_LOWER: reg
  SERUM_ALBUMIN_NORM_RANGE_UPPER: reg
  SERUM_ALBUMIN_PRERESECTION: reg
  SEX: cls
  SLIDE_TYPE: cls
  TISSUE_SOURCE_SITE: cls
  TUMOR_STATUS: cls
  VASCULAR_INVASION: cls
  WEIGHT: reg
  YEAR_OF_INITIAL_PATHOLOGIC_DIAGNOSIS: reg
tasks_to_run:
- ABLATION_EMBOLIZATION_TX_ADJUVANT
- AFP_AT_PROCUREMENT
- AFP_NORM_RANGE_LOWER
- AFP_NORM_RANGE_UPPER
- AGE
- AJCC_METASTASIS_PATHOLOGIC_PM
- AJCC_NODES_PATHOLOGIC_PN
- AJCC_PATHOLOGIC_TUMOR_STAGE
- AJCC_STAGING_EDITION
- AJCC_TUMOR_PATHOLOGIC_PT
- BILIRUBIN_TOTAL
- BILIRUBIN_TOTAL_NORM_RANGE_LOWER
- BILIRUBIN_TOTAL_NORM_RANGE_UPPER
- CHILD_PUGH_CLASSIFICATION
- CREATININE_LEVEL_PRERESECTION
- CREATININE_NORM_RANGE_LOWER
- CREATININE_NORM_RANGE_UPPER
- DAYS_TO_INITIAL_PATHOLOGIC_DIAGNOSIS
- DEFINITIVE_SURGICAL_PROCEDURE
- DFS_MONTHS
- DFS_STATUS
- ECOG_SCORE
- ETHNICITY
- FAMILY_HISTORY_CANCER_NUMBER_RELATIVES
- FAMILY_HISTORY_OF_CANCER
- GRADE
- HEIGHT
- HEPATIC_INFLAMMATION_ADJ_TISSUE
- HISTOLOGICAL_DIAGNOSIS
- HISTORY_HEPATO_CARCINOMA_RISK_FACTORS
- HISTORY_NEOADJUVANT_TRTYN
- HISTORY_OTHER_MALIGNANCY
- ICD_O_3_HISTOLOGY
- ISHAK_FIBROSIS_SCORE
- NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT
- OS_MONTHS
- OS_STATUS
- OTHER_HEPATO_CARCINOMA_RISK_FACTORS
- PHARMACEUTICAL_TX_ADJUVANT
- PLATELET_COUNT_PRERESECTION
- PLATELET_NORM_RANGE_LOWER
- PLATELET_NORM_RANGE_UPPER
- PROSPECTIVE_COLLECTION
- PROTHROMBIN_TIME_INR_AT_PROCUREMENT
- PROTHROMBIN_TIME_NORM_RANGE_UPPER
- PROTHROM_TIME_INR_NORM_RANGE_LOWER
- RACE
- RADIATION_TREATMENT_ADJUVANT
- RESIDUAL_TUMOR
- RETROSPECTIVE_COLLECTION
- SAMPLE_COUNT
- SERUM_ALBUMIN_NORM_RANGE_LOWER
- SERUM_ALBUMIN_NORM_RANGE_UPPER
- SERUM_ALBUMIN_PRERESECTION
- SEX
- TISSUE_SOURCE_SITE
- TUMOR_STATUS
- VASCULAR_INVASION
- WEIGHT
- YEAR_OF_INITIAL_PATHOLOGIC_DIAGNOSIS
- SLIDE_TYPE
- AJCC_PATHOLOGIC_TUMOR_STAGE_reduced
label_dict:
  ABLATION_EMBOLIZATION_TX_ADJUVANT:
    'NO': 0
    'YES': 1
  AJCC_METASTASIS_PATHOLOGIC_PM:
    M0: 0
    M1: 1
    MX: 2
  AJCC_NODES_PATHOLOGIC_PN:
    N0: 0
    N1: 1
    NX: 2
  AJCC_PATHOLOGIC_TUMOR_STAGE:
    Stage I: 0
    Stage II: 1
    Stage III: 2
    Stage IIIA: 3
    Stage IIIB: 4
    Stage IIIC: 5
    Stage IV: 6
    Stage IVA: 7
    Stage IVB: 8
  AJCC_PATHOLOGIC_TUMOR_STAGE_reduced:
    Stage I: 0
    Stage II: 1
    Stage III: 2
    Stage IV: 3
  AJCC_STAGING_EDITION:
    4th: 0
    5th: 1
    6th: 2
    7th: 3
  AJCC_TUMOR_PATHOLOGIC_PT:
    T1: 0
    T2: 1
    T2a: 2
    T2b: 3
    T3: 4
    T3a: 5
    T3b: 6
    T4: 7
    TX: 8
  CHILD_PUGH_CLASSIFICATION:
    A: 0
    B: 1
    C: 2
  DEFINITIVE_SURGICAL_PROCEDURE:
    Extended Lobectomy: 0
    Lobectomy: 1
    Other (specify): 2
    Segmentectomy, Multiple: 3
    Segmentectomy, Single: 4
    Total Hepatectomy with Transplant: 5
  DFS_STATUS:
    0:DiseaseFree: 0
    1:Recurred/Progressed: 1
  ETHNICITY:
    HISPANIC OR LATINO: 0
    NOT HISPANIC OR LATINO: 1
  FAMILY_HISTORY_OF_CANCER:
    'NO': 0
    'YES': 1
  GRADE:
    G1: 0
    G2: 1
    G3: 2
    G4: 3
  HEPATIC_INFLAMMATION_ADJ_TISSUE:
    Mild: 0
    Severe: 1
  HISTOLOGICAL_DIAGNOSIS:
    Fibrolamellar Carcinoma: 0
    Hepatocellular Carcinoma: 1
    Hepatocholangiocarcinoma (Mixed): 2
  HISTORY_HEPATO_CARCINOMA_RISK_FACTORS:
    Alcohol consumption: 0
    Alcohol consumption|Hepatitis B: 1
    Alcohol consumption|Hepatitis B|Hepatitis C: 2
    Alcohol consumption|Hepatitis B|Hepatitis C|Hemochromatosis: 3
    Alcohol consumption|Hepatitis C: 4
    Alcohol consumption|Hepatitis C|Non-Alcoholic Fatty Liver Disease: 5
    Alcohol consumption|Non-Alcoholic Fatty Liver Disease: 6
    Alcohol consumption|Non-Alcoholic Fatty Liver Disease|Other: 7
    Alcohol consumption|Other: 8
    Alpha-1 Antitrypsin Deficiency|Other: 9
    Hemochromatosis: 10
    Hepatitis B: 11
    Hepatitis B|Hepatitis C: 12
    Hepatitis B|Non-Alcoholic Fatty Liver Disease: 13
    Hepatitis B|Other: 14
    Hepatitis C: 15
    Hepatitis C|Hemochromatosis: 16
    Hepatitis C|Other: 17
    No History of Primary Risk Factors: 18
    Non-Alcoholic Fatty Liver Disease: 19
    Non-Alcoholic Fatty Liver Disease|Other: 20
    Other: 21
  HISTORY_NEOADJUVANT_TRTYN:
    'No': 0
    'Yes': 1
  HISTORY_OTHER_MALIGNANCY:
    'No': 0
    'Yes': 1
  ICD_O_3_HISTOLOGY:
    8170/3: 0
    8171/3: 1
    8173/3: 2
    8174/3: 3
    8180/3: 4
    8310/3: 5
  ISHAK_FIBROSIS_SCORE:
    0 - No Fibrosis: 0
    1,2 - Portal Fibrosis: 1
    3,4 - Fibrous Speta: 2
    5 - Nodular Formation and Incomplete Cirrhosis: 3
    6 - Established Cirrhosis: 4
  NEW_TUMOR_EVENT_AFTER_INITIAL_TREATMENT:
    'NO': 0
    'YES': 1
    '[Unknown]': 2
  OS_STATUS:
    0:LIVING: 0
    1:DECEASED: 1
  OTHER_HEPATO_CARCINOMA_RISK_FACTORS:
    Chronic hepatitis, either viral or autoimmune: 0
    Cirrhosis, Alcohol abuse: 1
    Cryptogenic Cirrhosis: 2
    Gilbert's syndrome.: 3
    HBcAB total (+), HBsAg (-), HBcIgm Ab (-): 4
    Hepatic Encephalopathy: 5
    Liver Cirrhosis, Moderate alcohol use on weekends: 6
    Male, IDDM for 30+years: 7
    Moderate alcohol consumption, anti TB drug used for TB positive testing: 8
    Sarcoidosis: 9
    Smoking: 10
    Tobacco use: 11
    Worker at steel factory: 12
    cirrhosis: 13
    extensive tobacco history: 14
    former smoker: 15
    hepatic cirrhosis: 16
    morbid obesity, tobacco use: 17
    primary biliary cirrhosis: 18
    smoker: 19
    smoking: 20
    tattoos: 21
    tobacco: 22
    tobacco, birth control bills: 23
  PHARMACEUTICAL_TX_ADJUVANT:
    'NO': 0
    'YES': 1
  PROSPECTIVE_COLLECTION:
    'NO': 0
    'YES': 1
  RACE:
    AMERICAN INDIAN OR ALASKA NATIVE: 0
    ASIAN: 1
    BLACK OR AFRICAN AMERICAN: 2
    WHITE: 3
  RADIATION_TREATMENT_ADJUVANT:
    'NO': 0
    'YES': 1
  RESIDUAL_TUMOR:
    R0: 0
    R1: 1
    R2: 2
    RX: 3
  RETROSPECTIVE_COLLECTION:
    'NO': 0
    'YES': 1
  SEX:
    Female: 0
    Male: 1
  SLIDE_TYPE:
    DX1: 0
    DX2: 1
    DX3: 2
  TISSUE_SOURCE_SITE:
    2V: 0
    2Y: 1
    4R: 2
    5C: 3
    5R: 4
    BC: 5
    BW: 6
    CC: 7
    DD: 8
    ED: 9
    EP: 10
    FV: 11
    G3: 12
    GJ: 13
    HP: 14
    K7: 15
    LG: 16
    MI: 17
    MR: 18
    NI: 19
    O8: 20
    PD: 21
    QA: 22
    RC: 23
    RG: 24
    T1: 25
    UB: 26
    WJ: 27
    WQ: 28
    WX: 29
    XR: 30
    YA: 31
    ZP: 32
    ZS: 33
  TUMOR_STATUS:
    TUMOR FREE: 0
    WITH TUMOR: 1
  VASCULAR_INVASION:
    Macro: 0
    Micro: 1
